mapping_channel=official
mapping_version=1.20.1
mod_id=worldprotect
mod_name=WorldProtect
package_name = CreateLazyTick
display_name = CLT
publish_version = release


mod_license=MIT
mod_version=1.0-alpha
mod_group_id=com.PinkCats
mod_authors=PinkCats
mod_description=A MinecraftMod for your save secure.


mixin_version = 0.8.5
cc_tweaked_enable = false
cc_tweaked_minecraft_version = 1.20.1
cc_tweaked_version = 1.105.0


ct_enabled = true
ct_minecraft_version = 1.20.1
ct_version = 14.0.17
ct_annotation_processor_version = 3.0.0.15
ct_create_version =  4.0.15
ct_create_id = 4548572

# dependency versions
ponder_version = 1.0.80
jei_minecraft_version = 1.20.1
jei_version = 15.19.0.85
curios_minecraft_version = 1.20.1
curios_version = 5.3.1



jade_id = 6106101
architectury_version=9.1.12
rhino_version=2001.2.3-build.10
kubejs_version=2001.6.5-build.17
mixin_extras_version = 0.4.1

curseforge_id =1352204
modrinth_id =DebMSCVn
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.8
forge_version_range=[47,)
loader_version_range=[47,)


# create
create_minecraft_version = 1.20.1
flywheel_minecraft_version = 1.20.1
create_version = 0.5.1.j-55
flywheel_version = 0.6.11-13
registrate_version = MC1.20-1.3.3
parchment_version = 2023.06.26

# gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.logging.level=quiet




# JDBC driver version
# see https://dev.mysql.com/doc/relnotes/connector-j/en/ for latest version
jdbc_version=9.3.0